export const PERSONAL_QUALITIES = {
  "en-us": [
    "Analytical",
    "Self-Directed",
    "Collaborative",
    "Proactive",
    "Organized",
    "Flexible",
  ],
  "pt-br": [
    "Analítico",
    "Autodidata",
    "Colaborativo",
    "Proativo",
    "Organizado",
    "Flexível",
  ],
} as const;

export interface Skill {
  name: string;
  icon: string;
  monotone?: boolean;
}

export const SKILL_CATEGORIES = [
  {
    titleEN: "Programming Languages",
    titlePT: "Linguagens de Programação",
    skills: [
      { name: "JavaScript", icon: "devicon:javascript" },
      { name: "Python", icon: "devicon:python" },
      { name: "C#", icon: "devicon:csharp" },
    ] as Skill[],
  },
  {
    titleEN: "Libraries & Frameworks",
    titlePT: "Bibliotecas & Frameworks",
    skills: [
      { name: "React.js", icon: "devicon:react" },
      { name: "Angular", icon: "devicon:angular" },
      { name: "Vue.js", icon: "devicon:vuejs" },
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Nuxt.js", icon: "devicon:nuxtjs" },
      { name: "TypeScript", icon: "devicon:typescript" },
      { name: "jQuery", icon: "devicon:jquery" },
      { name: "Styled Components", icon: "devicon:styledcomponents" },
      { name: "Tailwind CSS", icon: "devicon:tailwindcss" },
      { name: "Bootstrap", icon: "devicon:bootstrap" },
      { name: "Express", icon: "devicon:express", monotone: true },
      { name: "Prisma", icon: "devicon:prisma" },
      { name: "Socket.io", icon: "devicon:socketio", monotone: true },
      { name: "Nest.js", icon: "devicon:nestjs" },
      { name: "Django", icon: "logos:django-icon" },
      { name: "Flask", icon: "devicon:flask", monotone: true },
      { name: "Entity Framework", icon: "devicon:dotnetcore" },
      { name: "AutoMapper", icon: "devicon:csharp" },
      { name: "Moq", icon: "devicon:csharp" },
      { name: "xUnit", icon: "devicon:dotnetcore" },
    ] as Skill[],
  },
  {
    titleEN: "Databases",
    titlePT: "Bancos de Dados",
    skills: [
      { name: "PostgreSQL", icon: "devicon:postgresql" },
      { name: "MySQL", icon: "devicon:mysql" },
      { name: "Microsoft SQL Server", icon: "devicon:microsoftsqlserver" },
      { name: "MongoDB", icon: "devicon:mongodb" },
    ] as Skill[],
  },
  {
    titleEN: "Development Tools",
    titlePT: "Ferramentas de Desenvolvimento",
    skills: [
      { name: "Figma", icon: "devicon:figma" },
      { name: "Canva", icon: "devicon:canva" },
      { name: "Postman", icon: "devicon:postman" },
      { name: "DevTools", icon: "devicon:chrome" },
    ] as Skill[],
  },
  {
    titleEN: "Testing & Automation",
    titlePT: "Testes & Automação",
    skills: [
      { name: "Jest", icon: "logos:jest" },
      { name: "Selenium", icon: "devicon:selenium" },
      { name: "Scrapy", icon: "devicon:python" },
    ] as Skill[],
  },
  {
    titleEN: "Infrastructure & DevOps",
    titlePT: "Infraestrutura & DevOps",
    skills: [
      { name: "GitHub Actions", icon: "devicon:githubactions" },
      { name: "Azure DevOps", icon: "devicon:azure" },
      { name: "Docker", icon: "devicon:docker" },
      { name: "Ansible", icon: "devicon:ansible" },
      { name: "NGINX", icon: "logos:nginx" },
      { name: "RabbitMQ", icon: "devicon:rabbitmq" },
    ] as Skill[],
  },
] as const;

export const EXPERIENCES = [
  {
    company: "Marttech - Desenvolvimento de Software",
    positionEN: "Mid-level Front-end Developer",
    positionPT: "Desenvolvedor Front-end Pleno",
    locationEN: "Toledo, Paraná, Brazil",
    locationPT: "Toledo, Paraná, Brasil",
    startDate: "2024-07",
    endDate: "2025-08",
    descriptionEN: [
      "Gathered technical requirements from clients and documented system impacts.",
      "Prioritized tasks and organized sprints in Azure DevOps.",
      "Implemented user interfaces in React.js following usability guidelines.",
      "Developed reusable components with Material UI.",
      "Optimized MapBox polygon and layer implementations, reducing load time by 80% and memory usage from 6GB to 2GB.",
      "Refactored parts of the application architecture, addressing performance and usability issues.",
    ],
    descriptionPT: [
      "Levantei requisitos técnicos junto ao cliente e documentei os impactos no sistema.",
      "Priorizei demandas e organizei sprints no Azure DevOps.",
      "Implementei interfaces em React.js seguindo diretrizes de usabilidade.",
      "Desenvolvi componentes reutilizáveis com Material UI.",
      "Otimizei a implementação de polígonos e camadas no MapBox, reduzindo o tempo de carregamento em 80% e o uso de memória de 6GB para 2GB.",
      "Refatorei partes da arquitetura da aplicação, corrigindo problemas de desempenho e usabilidade.",
    ],
    technologies: [
      "React.js",
      "Material UI",
      "MapBox",
      "Azure DevOps",
      "TypeScript",
    ],
  },
  {
    company: "Ibrowse Consultoria e Informática",
    positionEN: "Mid-level Development Analyst",
    positionPT: "Analista de Desenvolvimento Pleno",
    locationEN: "Porto Alegre, Rio Grande do Sul, Brazil",
    locationPT: "Porto Alegre, Rio Grande do Sul, Brasil",
    startDate: "2023-08",
    endDate: "2024-01",
    descriptionEN: [
      "Supported internal and external teams with technical demands.",
      "Developed and fixed features in Angular applications.",
      "Defined architecture and design patterns for the application and new modules.",
      "Configured CI/CD pipelines and managed GitLab repositories.",
      "Created unit tests using Karma with 77% overall code coverage.",
      "Reviewed code and tracked deliveries in ClickUp, ensuring compliance with internal standards.",
    ],
    descriptionPT: [
      "Apoiei equipes internas e externas no atendimento de demandas técnicas.",
      "Desenvolvi e corrigi funcionalidades em aplicações Angular.",
      "Defini arquitetura e padrões de design para a aplicação e novos módulos.",
      "Configurei pipelines de CI/CD e administrei repositórios no GitLab.",
      "Criei testes unitários usando Karma com 77% de cobertura global de código.",
      "Revisei código e acompanhei entregas no ClickUp, garantindo conformidade com os padrões internos.",
    ],
    technologies: [
      "Angular",
      "GitLab",
      "CI/CD",
      "Karma",
      "ClickUp",
      "TypeScript",
    ],
  },
  {
    company: "INOVA - Polo de Inovação IFAM",
    positionEN: "Angular Front-end Web Developer",
    positionPT: "Desenvolvedor Web Front-end Angular",
    locationEN: "Manaus, Amazonas, Brazil",
    locationPT: "Manaus, Amazonas, Brasil",
    startDate: "2023-03",
    endDate: "2023-07",
    descriptionEN: [
      "Refactored outdated Angular pages and components.",
      "Created new screens and workflows to expand the application.",
      "Fixed critical bugs reported by end users.",
      "Mentored three students on technical activities, supervising deliveries and professional development.",
    ],
    descriptionPT: [
      "Refatorei páginas e componentes Angular desatualizados.",
      "Criei novas telas e fluxos para ampliar a aplicação.",
      "Corrigi bugs críticos reportados pelos usuários finais.",
      "Orientei 3 alunos em atividades técnicas, supervisionando entregas e capacitação profissional.",
    ],
    technologies: ["Angular", "TypeScript", "Angular Material"],
  },
  {
    company: "ClearSale",
    positionEN: "Information Technology Analyst",
    positionPT: "Analista de Tecnologia da Informação",
    locationEN: "São Paulo, São Paulo, Brazil",
    locationPT: "São Paulo, São Paulo, Brasil",
    startDate: "2022-01",
    endDate: "2022-12",
    descriptionEN: [
      "Created interfaces and components in Vue.js.",
      "Maintained and enhanced features in C# and jQuery.",
      "Modeled and managed data in SQL Server.",
      "Documented application workflows for development teams.",
      "Analyzed production errors and reported moderate failures.",
      "Developed unit tests to ensure code quality.",
    ],
    descriptionPT: [
      "Criei interfaces e componentes em Vue.js.",
      "Mantive e evoluí funcionalidades em C# e jQuery.",
      "Modelei e gerenciei dados no SQL Server.",
      "Documentei fluxos da aplicação para equipes de desenvolvimento.",
      "Analisei erros em produção e reportei falhas moderadas.",
      "Desenvolvi testes unitários para garantir qualidade do código.",
    ],
    technologies: ["Vue.js", "C#", "jQuery", "SQL Server"],
  },
  {
    company: "INOVA - Polo de Inovação IFAM",
    positionEN: "Angular Front-end Web Developer",
    positionPT: "Desenvolvedor Web Front-end Angular",
    locationEN: "Manaus, Amazonas, Brazil",
    locationPT: "Manaus, Amazonas, Brasil",
    startDate: "2021-09",
    endDate: "2022-03",
    descriptionEN: [
      "Developed screens and components in Angular.",
      "Improved application design and layout with Angular Material.",
      "Analyzed visual errors and corrected UI/UX inconsistencies.",
      "Collaborated with back-end team to align integrations.",
    ],
    descriptionPT: [
      "Desenvolvi telas e componentes em Angular.",
      "Melhorei design e layout da aplicação com Angular Material.",
      "Analisei erros visuais e corrigi inconsistências de UI/UX.",
      "Colaborei com equipe de back-end para alinhar integrações.",
    ],
    technologies: ["Angular", "Angular Material", "TypeScript"],
  },
  {
    company: "BeeApp",
    positionEN: "Vue Front-end Web Developer",
    positionPT: "Desenvolvedor Web Front-end Vue",
    locationEN: "Primavera do Leste, Mato Grosso, Brazil",
    locationPT: "Primavera do Leste, Mato Grosso, Brasil",
    startDate: "2021-10",
    endDate: "2021-12",
    descriptionEN: [
      "Created modular Vue.js components using Vuetify.",
      "Adapted pages for mobile devices, ensuring responsiveness.",
      "Migrated legacy PHP systems to Vue.js.",
      "Developed SSR with Nuxt, increasing Lighthouse SEO score from 65 to 80.",
      "Modeled front-end architecture for a new project.",
      "Configured UI libraries to standardize the application.",
    ],
    descriptionPT: [
      "Criei componentes Vue.js modulares usando Vuetify.",
      "Adaptei páginas para dispositivos mobile, garantindo responsividade.",
      "Migrei sistemas legados de PHP para Vue.js.",
      "Desenvolvi SSR com Nuxt, aumentando nota de SEO no Lighthouse de 65 para 80.",
      "Modelei a arquitetura de front-end para o novo projeto.",
      "Configurei bibliotecas de UI para padronizar a aplicação.",
    ],
    technologies: ["Vue.js", "Vuetify", "Nuxt.js", "PHP"],
  },
] as const;

export const TECHNOLOGIES = [
  "JavaScript",
  "Python",
  "C#",
  "React.js",
  "Angular",
  "Vue.js",
  "Next.js",
  "Nuxt.js",
  "TypeScript",
  "jQuery",
  "Styled Components",
  "Tailwind CSS",
  "Bootstrap",
  "Express",
  "Socket.io",
  "Nest.js",
  "Django",
  "Flask",
  "Entity Framework",
  "PostgreSQL",
  "Figma",
  "Jest",
  "Selenium",
  "Docker",
] as const;
